apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    project: roboshop
    tier: db 
spec:
  replicas: 1
  selector:
    matchLabels: # replicaset labels
      app: mongodb
      project: roboshop 
      tier: db
  template:    # pod labels 
    metadata:
      labels:
        app: mongodb
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mongodb
        image: joindevops/mongodb:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 27017

--- 
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    app: mongodb
    project: roboshop
    tier: db
  ports:
  - name: mongodb
    protocol: TCP
    port: 27017     # service port 
    targetPort: 27017  # container port 