---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels: # these labels are deployment labels
    app: redis
    project: roboshop
    tier: db 
spec:
  replicas: 1
  selector:
    matchLabels: # replicaset labels, these labels are used to find the pods
      app: redis
      project: roboshop
      tier: db
  template:    # pod labels 
    metadata:
      labels:
        app: redis
        project: roboshop
        tier: db
    spec:
      containers:
      - name: redis
        image: redis
        imagePullPolicy: Always
          
--- 
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    app: redis
    project: roboshop
    tier: redis
  ports:
  - name: redis
    protocol: TCP
    port: 6379     # service port 
    targetPort: 6379  # container port 